# -------
# Library
# -------

library:
  name: KotBilling
  api: 21
  github: MFlisar/KotBilling
  maven: io.github.mflisar.kotbilling
  maven-main-library: library
  multiplatform: false
  platforms:
    - android
  screenshots:  []
  branch: master
  demo: true

# ------------
# Dependencies
# ------------

dependencies:
  compose-multiplatform: 1.7.0 # https://github.com/JetBrains/compose-multiplatform/releases
  jetpack-compose-runtime: 1.7.1 # https://developer.android.com/jetpack/androidx/releases/compose-runtime
  jetpack-compose-material3: 1.3.0 # https://developer.android.com/jetpack/androidx/releases/compose-material3
  experimental: false

# ------------
# Groups
# ------------

groups: []

# ------------
# Modules
# ------------

modules:
  - name: library
    group: core
    description: A kotlin coroutine based solution for handling in app purchases with the android billing library.
    optional: false
    platforms:
      - android
    platforms-info: ""
    dependencies:
      - name: Play Billing
        link: https://developer.android.com/google/play/billing/integrate
        version: 7.1.1